[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
devolt = "A8Tx8hQwFY2mDuRG89dxiLBac1V3rJtkpPKvktc7uMkw"
test = "DQvxNCgYuPSoShYjpQepwuzhm9Fp2B7QXKGF8VMrSbky"

[registry]
url = "http://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
